{
 "title": "Applications",
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "NS",
    "label": "Namespace",
    "query": {
     "query": "label_values(kube_pod_container_info{}, namespace)"
    }
   },
   {
    "name": "APP",
    "label": "Application",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$NS\"}, container)"
    }
   },
   {
    "name": "POD",
    "label": "Pod",
    "query": {
     "query": "label_values(kube_pod_container_info{namespace=\"$NS\",container=\"$APP\"}, pod)"
    }
   }
  ]
 },
 "panels": [
  { "title": "Resources", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_memory_working_set_bytes{namespace=\"$NS\", container=~\"$APP\"})",
     "legendFormat": "$APP"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{ namespace=\"$NS\", pod=~\"$POD\", resource=\"memory\"}\n)",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{ namespace=\"$NS\", pod=~\"$POD\", resource=\"memory\"}\n)",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "sum(node_namespace_pod_container:container_cpu_usage_seconds_total:sum_irate{namespace=\"$NS\", pod=~\"$POD\",container=~\"$APP\"}) by (container)",
     "legendFormat": "{{ container }}"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_requests{ namespace=\"$NS\", pod=~\"$POD\", resource=\"cpu\"}\n)",
     "legendFormat": "requests"
    },
    {
     "expr": "sum(\n    kube_pod_container_resource_limits{ namespace=\"$NS\", pod=~\"$POD\", resource=\"cpu\"}\n)",
     "legendFormat": "limits"
    }
   ]
  },
  {
   "title": "Storage",
   "type": "graph",
   "description": "WARNING: Any PVCs that are not bound to a running pod will not show up.",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "repeat": "persistentvolumeclaim",
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_used_bytes {namespace=\"$NS\", persistentvolumeclaim=~\".*$APP.*\"}))",
     "legendFormat": "Used"
    },
    {
     "expr": "(max by (persistentvolumeclaim,namespace) (kubelet_volume_stats_capacity_bytes {namespace=\"$NS\", persistentvolumeclaim=~\".*$APP.*\"}))",
     "legendFormat": "Capacity"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Requests Rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "reqps" } },
     "targets": [
      {
       "expr": "sum(rate(traefik_service_requests_total{service=~\"$NS.*$APP.*\"}[1m])) by (code,method)",
       "legendFormat": "{{ method }} - {{ code }} "
      }
     ]
    },
    {
     "title": "Requests Count",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 16 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum(increase(traefik_service_requests_total{service=~\"$NS.*$APP.*\"}[1m])) by (code,method)",
       "legendFormat": "{{ method }} - {{ code }} "
      }
     ]
    },
    {
     "title": "Average Response Time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 22 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(traefik_service_request_duration_seconds_sum{service=~\"$NS.*$APP.*\"}[1m]) / increase(traefik_service_request_duration_seconds_count{service=~\"$NS.*$APP.*\"}[1m])",
       "legendFormat": "{{ method }} {{ code }}"
      }
     ]
    }
   ]
  },
  { "title": "Logs", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Rate",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {
     "expr": "sum without(filename,pod)(rate({namespace=\"$NS\",container=\"$APP\",pod=~\"$POD\"}[$__interval]))",
     "legendFormat": "{{ app }}",
     "resolution": 3
    }
   ]
  },
  {
   "type": "logs",
   "gridPos": { "h": 15, "w": 24, "x": 0, "y": 22 },
   "targets": [
    {
     "expr": "{namespace=\"$NS\",container=\"$APP\",pod=~\"$POD\"}"
    }
   ]
  }
 ]
}