#!/usr/bin/env bash

REBUILD(){
    echo "***************"
    echo "* Rebuild env *"
    echo "***************"

    IAAS

    sed -i 's/10\.0\.2\.15/192\.168\.60\.10/g' kubeconfig-dev

    UP_NS

    HSYNCLONGHORN

    HSYNC

    echo "***************"
    echo "*    Done     *"
    echo "***************"
}

IAAS(){
    cd infrastructure/bare-metal
    ansible-playbook -i inventories/dev/hosts playbook/infrastructure.yml -t hardening::upgrade
    ansible-playbook -i inventories/dev/hosts playbook/infrastructure.yml
    cd ../..
}

UP_NS(){
    cd kubernetes
    cd namespaces
    helmfile -e dev sync
    cd ..
}

HSYNCLONGHORN(){
    cd kubernetes
    helmfile -e dev -l name=longhorn sync
    sleep 60
    cd ..
}

HSYNC(){
    cd kubernetes
    helmfile -e dev sync
    cd ..
    sleep 10
    kubectl get pods --all-namespaces
}


case $1 in
    "REBUILD")
        REBUILD
        ;;
    "UP_NS")
        UP_NS
        ;;
    "HSYNC")
        HSYNC
        ;;
esac
